apiVersion: v1
kind: Pod
metadata:
  name: 2ndpod
spec:
  containers:
  - name: simple-container
    image: nginx
  tolerations:
  - key: "devops"
    operator: "Equal"
    value: "engineer"
    effect: "NoSchedule"
