apiVersion: v1
kind: Pod
metadata:
  name: al-nafi-pod-2
  namespace: al-nafi
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "2Gi"
        cpu: "2"
      limits:
        memory: "2.5Gi"
        cpu: "4"  
