apiVersion: v1
kind: Pod
metadata:
  name: al-nafi-web-app
spec:
  containers:
  - name: event-simulator
    image: kodekloud/event-simulator
    env:
    - name: LOG_HANDLERS
      value: file
    volumeMounts:
    - name: al-nafi-app-logs
      mountPath: /log

  volumes:
  - name: al-nafi-app-logs
    hostPath:
      path: /tmp/logs
      type: Directory   
