apiVersion: v1
kind: Service
metadata:
  name: al-nafi-service
spec:
  ports:
  - nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: development
    tier: production
  type: NodePort
    
